### ISSUE TITLE
regex is wrong

### ISSUE THREAD

**Issue by smoes** [k4m4/ripple-regex#1]
I think a better regex would be 

`"r[0-9a-zA-Z]{24,34}"`

From the official doc:

* Between 25 and 35 characters in length
* Starts with the character r
* Uses alphanumeric characters, excluding the number "0" capital letter "O", capital letter "I", and lowercase letter "l"
* Case-sensitive

https://developers.ripple.com/accounts.html

If you want to be very precise, exclude "0", "O", "l" and "I"

**Comment by k4m4** [comment]
Thank you for your suggestion!
